[world]
kind = "WorldContract"
class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
original_class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x256aa98b2bc80895629019a277231250e83219f28c98aa8bb81d077a276146c"
transaction_hash = "0x3abfd5f1ffc2b608e33188776807d76f23c40f3c535ec330c908ec5744fef80"
block_number = 3
seed = "starkludo"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x755ab4a1ab291fa86148a886654868cff7aa3b9cb05668b4fc2bae4b2fce35d"
class_hash = "0x5cd57a1faec53ae7b0f89465e4c2a1b639fe1ac30fbb46007bd5a3ff4c9fb6b"
original_class_hash = "0x5cd57a1faec53ae7b0f89465e4c2a1b639fe1ac30fbb46007bd5a3ff4c9fb6b"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/starkludo-GameActions-72b46dc4.json"
reads = []
writes = []
init_calldata = []
tag = "starkludo-GameActions"
systems = [
    "restart",
    "terminate_game",
]
manifest_name = "starkludo-GameActions-72b46dc4"

[[contracts]]
kind = "DojoContract"
address = "0x22157de44f59dc4f2facb7f597dda9ea1834656e79a173ff9e0d6056837054d"
class_hash = "0x4b3c29628dab01e08eba58707af15743108c4e7d2e169555375efc8f1ee6e2c"
original_class_hash = "0x4b3c29628dab01e08eba58707af15743108c4e7d2e169555375efc8f1ee6e2c"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/starkludo-PlayerActions-20dad3ac.json"
reads = []
writes = []
init_calldata = []
tag = "starkludo-PlayerActions"
systems = [
    "create",
    "update_username",
]
manifest_name = "starkludo-PlayerActions-20dad3ac"

[[models]]
kind = "DojoModel"
class_hash = "0x142b55dcf7d81397c7c9a4e8d97235f7a441b8ecfbafcaf59d096a87ac7d446"
original_class_hash = "0x142b55dcf7d81397c7c9a4e8d97235f7a441b8ecfbafcaf59d096a87ac7d446"
abi = "manifests/dev/deployment/abis/models/starkludo-Game-5286f583.json"
tag = "starkludo-Game"
qualified_path = "starkludo::models::game::game"
manifest_name = "starkludo-Game-5286f583"

[[models.members]]
name = "id"
type = "u64"
key = true

[[models.members]]
name = "created_by"
type = "ContractAddress"
key = false

[[models.members]]
name = "game_status"
type = "GameStatus"
key = false

[[models.members]]
name = "game_mode"
type = "GameMode"
key = false

[[models.members]]
name = "player_green"
type = "felt252"
key = false

[[models.members]]
name = "player_yellow"
type = "felt252"
key = false

[[models.members]]
name = "player_blue"
type = "felt252"
key = false

[[models.members]]
name = "player_red"
type = "felt252"
key = false

[[models.members]]
name = "winner_1"
type = "felt252"
key = false

[[models.members]]
name = "winner_2"
type = "felt252"
key = false

[[models.members]]
name = "winner_3"
type = "felt252"
key = false

[[models.members]]
name = "next_player"
type = "felt252"
key = false

[[models.members]]
name = "number_of_players"
type = "u8"
key = false

[[models.members]]
name = "rolls_count"
type = "u256"
key = false

[[models.members]]
name = "rolls_times"
type = "u256"
key = false

[[models.members]]
name = "dice_face"
type = "u8"
key = false

[[models.members]]
name = "player_chance"
type = "ContractAddress"
key = false

[[models.members]]
name = "has_thrown_dice"
type = "bool"
key = false

[[models.members]]
name = "b0"
type = "felt252"
key = false

[[models.members]]
name = "b1"
type = "felt252"
key = false

[[models.members]]
name = "b2"
type = "felt252"
key = false

[[models.members]]
name = "b3"
type = "felt252"
key = false

[[models.members]]
name = "g0"
type = "felt252"
key = false

[[models.members]]
name = "g1"
type = "felt252"
key = false

[[models.members]]
name = "g2"
type = "felt252"
key = false

[[models.members]]
name = "g3"
type = "felt252"
key = false

[[models.members]]
name = "r0"
type = "felt252"
key = false

[[models.members]]
name = "r1"
type = "felt252"
key = false

[[models.members]]
name = "r2"
type = "felt252"
key = false

[[models.members]]
name = "r3"
type = "felt252"
key = false

[[models.members]]
name = "y0"
type = "felt252"
key = false

[[models.members]]
name = "y1"
type = "felt252"
key = false

[[models.members]]
name = "y2"
type = "felt252"
key = false

[[models.members]]
name = "y3"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x552147f9afe3a1587cf334876dd5e9b5b52200aabf22a0d7cd036625580b6c2"
original_class_hash = "0x552147f9afe3a1587cf334876dd5e9b5b52200aabf22a0d7cd036625580b6c2"
abi = "manifests/dev/deployment/abis/models/starkludo-Player-3bb81cb1.json"
tag = "starkludo-Player"
qualified_path = "starkludo::models::player::player"
manifest_name = "starkludo-Player-3bb81cb1"

[[models.members]]
name = "username"
type = "felt252"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false

[[models.members]]
name = "total_games_played"
type = "u256"
key = false

[[models.members]]
name = "total_games_won"
type = "u256"
key = false
