[world]
kind = "WorldContract"
class_hash = "0x5c4271c8cd454ceb8049d2b0724c99d12c2ef8077fc6ad325b18978f614aab0"
original_class_hash = "0x5c4271c8cd454ceb8049d2b0724c99d12c2ef8077fc6ad325b18978f614aab0"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x4e4a8cb96198772361acc30c71d81768bccc6c29501f211b0f0ca7045b194a4"
transaction_hash = "0x6c8c96163c93a23251256cedd16c15751b44196a7cff29726198f65aba14f70"
block_number = 3
seed = "starkludo"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x7b7ccc529c6d4cd2c857247c9c42ffa098aeb9a3c4718771825e054f98039e3"
class_hash = "0x4cecefc87acb36b188cec659cfde8d7cbfafaf8684297f7d66cadd573cbfec5"
original_class_hash = "0x4cecefc87acb36b188cec659cfde8d7cbfafaf8684297f7d66cadd573cbfec5"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/starkludo-GameActions-72b46dc4.json"
reads = []
writes = []
init_calldata = []
tag = "starkludo-GameActions"
systems = [
    "restart",
    "terminate_game",
]
manifest_name = "starkludo-GameActions-72b46dc4"

[[contracts]]
kind = "DojoContract"
address = "0x182a153535285af4bf98b00141f6ffe37edd898947e450b6a2c5d54c3b6e178"
class_hash = "0x23f585a946c3224f0993e7001e132dfc559a7683e520ef4c5beee9a5bc8dd65"
original_class_hash = "0x23f585a946c3224f0993e7001e132dfc559a7683e520ef4c5beee9a5bc8dd65"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/starkludo-PlayerActions-20dad3ac.json"
reads = []
writes = []
init_calldata = []
tag = "starkludo-PlayerActions"
systems = [
    "create",
    "update_username",
]
manifest_name = "starkludo-PlayerActions-20dad3ac"

[[models]]
kind = "DojoModel"
class_hash = "0x6f661d514e79ee250cef7baa203a0b994f3f9e2dd4cf4fa4ba991f43d11d939"
original_class_hash = "0x6f661d514e79ee250cef7baa203a0b994f3f9e2dd4cf4fa4ba991f43d11d939"
abi = "manifests/dev/deployment/abis/models/starkludo-Game-5286f583.json"
tag = "starkludo-Game"
qualified_path = "starkludo::models::game::game"
manifest_name = "starkludo-Game-5286f583"

[[models.members]]
name = "id"
type = "u64"
key = true

[[models.members]]
name = "created_by"
type = "ContractAddress"
key = false

[[models.members]]
name = "game_status"
type = "GameStatus"
key = false

[[models.members]]
name = "game_mode"
type = "GameMode"
key = false

[[models.members]]
name = "player_green"
type = "felt252"
key = false

[[models.members]]
name = "player_yellow"
type = "felt252"
key = false

[[models.members]]
name = "player_blue"
type = "felt252"
key = false

[[models.members]]
name = "player_red"
type = "felt252"
key = false

[[models.members]]
name = "winner_1"
type = "felt252"
key = false

[[models.members]]
name = "winner_2"
type = "felt252"
key = false

[[models.members]]
name = "winner_3"
type = "felt252"
key = false

[[models.members]]
name = "next_player"
type = "felt252"
key = false

[[models.members]]
name = "number_of_players"
type = "u8"
key = false

[[models.members]]
name = "rolls_count"
type = "u256"
key = false

[[models.members]]
name = "rolls_times"
type = "u256"
key = false

[[models.members]]
name = "dice_face"
type = "u8"
key = false

[[models.members]]
name = "player_chance"
type = "ContractAddress"
key = false

[[models.members]]
name = "has_thrown_dice"
type = "bool"
key = false

[[models.members]]
name = "b0"
type = "felt252"
key = false

[[models.members]]
name = "b1"
type = "felt252"
key = false

[[models.members]]
name = "b2"
type = "felt252"
key = false

[[models.members]]
name = "b3"
type = "felt252"
key = false

[[models.members]]
name = "g0"
type = "felt252"
key = false

[[models.members]]
name = "g1"
type = "felt252"
key = false

[[models.members]]
name = "g2"
type = "felt252"
key = false

[[models.members]]
name = "g3"
type = "felt252"
key = false

[[models.members]]
name = "r0"
type = "felt252"
key = false

[[models.members]]
name = "r1"
type = "felt252"
key = false

[[models.members]]
name = "r2"
type = "felt252"
key = false

[[models.members]]
name = "r3"
type = "felt252"
key = false

[[models.members]]
name = "y0"
type = "felt252"
key = false

[[models.members]]
name = "y1"
type = "felt252"
key = false

[[models.members]]
name = "y2"
type = "felt252"
key = false

[[models.members]]
name = "y3"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x552147f9afe3a1587cf334876dd5e9b5b52200aabf22a0d7cd036625580b6c2"
original_class_hash = "0x552147f9afe3a1587cf334876dd5e9b5b52200aabf22a0d7cd036625580b6c2"
abi = "manifests/dev/deployment/abis/models/starkludo-Player-3bb81cb1.json"
tag = "starkludo-Player"
qualified_path = "starkludo::models::player::player"
manifest_name = "starkludo-Player-3bb81cb1"

[[models.members]]
name = "username"
type = "felt252"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false

[[models.members]]
name = "total_games_played"
type = "u256"
key = false

[[models.members]]
name = "total_games_won"
type = "u256"
key = false
