kind = "DojoContract"
class_hash = "0x702e990d138e00312cc14d315fb12ce6186989ab889b1f365d4575f1d0a83cf"
original_class_hash = "0x702e990d138e00312cc14d315fb12ce6186989ab889b1f365d4575f1d0a83cf"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/starkludo-GameActions-72b46dc4.json"
reads = []
writes = []
init_calldata = []
tag = "starkludo-GameActions"
manifest_name = "starkludo-GameActions-72b46dc4"
